spring:
  application:
    name: product

  jpa:
    show-sql: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: cloud
    password: 19981002520qq
    url: jdbc:mysql://localhost:3306/product?useSSL=false&characterEncoding=utf-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

server:
  port: 9090
